module Problem101


title = "Problem 101: Optimum polynomial"
published_on = "Friday, 29th July 2005, 06:00 pm"
solved_by = 12016
difficulty_rating = "35%"
content = """
If we are presented with the first k terms of a sequence it is impossible to say with certainty the value of the next term, as there
are infinitely many polynomial functions that can model the sequence.

As an example, let us consider the sequence of cube numbers. This is defined by the generating function, 
uₙ = n³: 1, 8, 27, 64, 125, 216, ...

Suppose we were only given the first two terms of this sequence. Working on the principle that "simple is best" we should
assume a linear relationship and predict the next term to be 15 (common difference 7). Even if we were presented with the first
three terms, by the same principle of simplicity, a quadratic relationship should be assumed.

We shall define OP(k, n) to be the nᵗʰ term of the optimum polynomial generating function for the first k terms of a sequence. It
should be clear that OP(k, n) will accurately generate the terms of the sequence for n ≤ k, and potentially the first incorrect term
(FIT) will be OP(k, k+1); in which case we shall call it a bad OP (BOP).

As a basis, if we were only given the first term of sequence, it would be most sensible to assume constancy; that is, for n ≥ 2,
OP(1, n) = u₁.

Hence we obtain the following OPs for the cubic sequence:

            OP(1, n) = 11,        1, \e[1;91m1\e[0m, 1, ...
            OP(2, n) = 7n-6       1, 8, \e[1;91m15\e[0m, ...
            OP(3, n) = 6n²-11n+6  1, 8, 27, \e[1;91m58\e[0m, ...
            OP(4, n) = n³         1, 8, 27, 64, 125, ...

Clearly no BOPs exist for k ≥ 4.

By considering the sum of FITs generated by the BOPs (indicated in \e[1;91mred\e[0m above), we obtain 1 + 15 + 58 = 74.

Consider the following tenth degree polynomial generating function:

uₙ = 1 - n + n² - n³ + n⁴ - n⁵ + n⁶ - n⁷ + n⁸ - n⁹ + n¹⁰

Find the sum of FITs for the BOPs.
"""


end # module Problem101
