module Problem45


title = "Problem 45: Triangular, pentagonal, and hexagonal"
published_on = "Friday, 6th June 2003, 06:00 pm"
solved_by = 73568
difficulty_rating = "5%"
content = """
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle     Tₙ=n(n+1)/2    1, 3, 6, 10, 15, ...
Pentagonal   Pₙ=n(3n-1)/2   1, 5, 12, 22, 35, ...
Hexagonal    Hₙ=n(2n-1)     1, 6, 15, 28, 45, ...

It can be verified that T₂₈₅ = P₁₆₅ = H₁₄₃ = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
"""


end # module Problem45
