module Problem288


title = "Problem 288: An enormous factorial"
published_on = "Saturday, 17th April 2010, 01:00 pm"
solved_by = 1690
difficulty_rating = "35%"
content = """
For any prime p the number N(p,q) is defined by N(p,q) = ∑ₙ₌₀ ₜₒ _q Tₙ*pⁿ
with Tₙ generated by the following random number generator:

S₀ = 290797

Sₙ₊₁ = Sₙ² mod 50515093

Tₙ = Sₙ mod p

Let Nfac(p,q) be the factorial of N(p,q).
Let NF(p,q) be the number of factors p in Nfac(p,q).

You are given that NF(3,10000) mod 3²⁰=624955285.

Find NF(61,10⁷) mod 61¹⁰
"""


end # module Problem288
