module Problem2


title = "Problem 2: Even Fibonacci numbers"
published_on = "Friday, 19th October 2001, 06:00 pm"
solved_by = 774551
difficulty_rating = "5%"
content = """
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10
terms will be:

                                             1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued
terms.
"""


end # module Problem2
