module Problem297


title = "Problem 297: Zeckendorf Representation"
published_on = "Friday, 18th June 2010, 05:00 pm"
solved_by = 2840
difficulty_rating = "35%"
content = """
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
Starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89.

Every positive integer can be uniquely written as a sum of nonconsecutive terms of the Fibonacci sequence. For example, 100
= 3 + 8 + 89.
Such a sum is called the \e[1mZeckendorf representation\e[0m of the number.

For any integer n>0, let z(n) be the number of terms in the Zeckendorf representation of n.
Thus, z(5) = 1, z(14) = 2, z(100) = 3 etc.
Also, for 0<n<10⁶, ∑ z(n) = 7894453.

Find ∑ z(n) for 0<n<10¹⁷.
"""


end # module Problem297
