module Problem12


title = "Problem 12: Highly divisible triangular number"
published_on = "Friday, 8th March 2002, 06:00 pm"
solved_by = 227396
difficulty_rating = "5%"
content = """
The sequence of triangle numbers is generated by adding the natural numbers. So the 7ᵗʰ triangle number would be 1 + 2 + 3
+ 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

       \e[1m1\e[0m: 1
       \e[1m3\e[0m: 1,3
       \e[1m6\e[0m: 1,2,3,6
      \e[1m10\e[0m: 1,2,5,10
      \e[1m15\e[0m: 1,3,5,15
      \e[1m21\e[0m: 1,3,7,21
      \e[1m28\e[0m: 1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five divisors.
What is the value of the first triangle number to have over five hundred divisors?
"""


end # module Problem12
