module Problem44


title = "Problem 44: Pentagon numbers"
published_on = "Friday, 23rd May 2003, 06:00 pm"
solved_by = 61088
difficulty_rating = "5%"
content = """
Pentagonal numbers are generated by the formula, Pₙ=n(3n-1)/2. The first ten pentagonal numbers are:

                                         1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P₄ + P₇ = 22 + 70 = 92 = P₈. However, their difference, 70 - 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pⱼ and Pₖ, for which their sum and difference are pentagonal and D = |Pₖ - Pⱼ| is
minimised; what is the value of D?
"""


end # module Problem44
